sudo: false

# Choose a lightweight base image; we provide our own tools.
language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

env:
  - COMPONENT=client
  - COMPONENT=server

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  ./ci/build.sh

notifications:
  email: true

before_deploy:
  - mkdir bundle
  - cp `stack path --dist-dir`/build/trypurescript/trypurescript bundle/
  - cp LICENSE bundle/
  - tar czf trypurescript.tar.gz -C bundle/ .

deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file: trypurescript.tar.gz
  skip_cleanup: true
  on:
    tags: true
