resolver: lts-13.26
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
packages:
- '.'
extra-deps:
# purescript 0.14.0-rc5
- github: purescript/purescript
  commit: 7ecc42669c69682996f2196ba2eef6c4ca827348
  subdirs:
    - .
    - lib/purescript-ast
    - lib/purescript-cst
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1
