resolver: lts-17.6

packages:
  - "."

extra-deps:
  # purescript 0.14.3
  - github: purescript/purescript
    commit: b4c90a8bb6a1059f271f4211687192370fda81bc
    subdirs:
      - .
      - lib/purescript-cst
  - language-javascript-0.7.0.0

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
