resolver: lts-17.6
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
packages:
- '.'
extra-deps:
- purescript-0.14.1
- purescript-ast-0.1.1.0
- purescript-cst-0.1.1.0
- happy-1.20.0
- language-javascript-0.7.0.0
