resolver: lts-17.6
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
packages:
- '.'
extra-deps:
- purescript-0.14.2
- purescript-cst-0.2.0.0
- happy-1.20.0
- language-javascript-0.7.0.0
