name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build_server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: Cache stack
        uses: actions/cache@v1
        with:
          path: $HOME/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build server code
        run: |
          timeout 45m stack --no-terminal -j1 build

  build_client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Build client code
        run: |
          cd client
          npm install
          npm run build
          npm run test
          npm run build:production

  upload_server:
    name: Build server assets
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'created'
    needs: build_server
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-setup-ghc: true
      - run: |
          mkdir server-bundle
          cp $(stack path --dist-dir)/build/trypurescript/trypurescript server-bundle/
          cp LICENSE server-bundle/
          cp -r deploy/ server-bundle/
          cp -r staging/ server-bundle/
          tar czf trypurescript-server.tar.gz -C server-bundle/ .
          ls

  upload_client:
    name: Build client assets
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'created'
    needs: build_client
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir client-bundle
          cp LICENSE client-bundle/
          cp -r client/public/ client-bundle/
          tar czf trypurescript-client.tar.gz -C client-bundle/ .
          ls

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - upload_server
      - upload_client
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            trypurescript-server.tar.gz
            trypurescript-client.tar.gz
